{% set name = "httpx-negotiate-sspi" %}
{% set version = "0.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/httpx_negotiate_sspi-{{ version }}.tar.gz
  sha256: cbf5ae118f33c92986eedffe18913e46252788ae97cd43f75f8efbad5725d0f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry >=1.0
    - poetry-core
    - pip
  run:
    - __unix  # [unix]
    - __win  # [win]
    - python >=3.8
    - pywin32 >=223  # [win]
    - httpx >0.16,<0.27

test:
  imports:
    - httpx_negotiate_sspi  # [win]

about:
  home: https://github.com/rob-blackbourn/httpx-negotiate-sspi
  summary: SSPI authentication for httpx
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
