{% set name = "httpx-negotiate-sspi" %}
{% set version = "0.28.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/httpx_negotiate_sspi-{{ version }}.tar.gz
  sha256: d7bd8f0d8cb9922460cbac868dd087b65ed961711132b6ed3a9d9c61b115629a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry >=1.0
    - poetry-core
    - pip
  run:
    - pywin32-on-windows
    - python >={{ python_min }}
  run_constrained:
    - httpx >0.16,<0.29
    - httpx2 >=2.0.0
    - pywin32 >=223

test:
  requires:
    - python {{ python_min }}
    - httpx2
  imports:
    - httpx_negotiate_sspi  # [win]

about:
  home: https://github.com/rob-blackbourn/httpx-negotiate-sspi
  summary: SSPI authentication for httpx
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
